// Offline numeric witness. No SDK, G1Deploy instance, DDS or command writer.
// Captured gatherers, StateLogger, MotionSequence and math helpers are real
// source copies. Sensor values / reference arrays are injected by the caller;
// acquisition, real-time scheduling, CSV reading and mode transitions are NOT.
#include <algorithm>
#include <cmath>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>
#include "state_logger.hpp"
#include "robot_parameters.hpp"
#include "utils.hpp"
#include "motion_data_reader.hpp"

class ObservationWitness {
 public:
  double control_dt_ = 0.02;
  int current_frame_ = 0;
  int saved_frame_for_observation_window_ = 0;
  bool has_upper_body_data_ = false;
  std::array<double, 17> upper_body_joint_positions_buffer_{};
  std::array<double, 17> upper_body_joint_velocities_buffer_{};
  OperatorState operator_state;
  std::unique_ptr<StateLogger> state_logger_;
  std::shared_ptr<MotionSequence> current_motion_;
  DataBuffer<HeadingState> heading_state_buffer_;
  std::array<double, 4> init_ref_data_root_rot_array_{};

  ObservationWitness(int count, const double* quaternion, const double* joint,
                     const double* velocity, const double* initial_robot) {
    if (count < 2 || count > 100000) throw std::invalid_argument("invalid frame count");
    // CSV is always disabled, including directory creation and metadata writes.
    state_logger_ = std::make_unique<StateLogger>("", 10, 29, 29, 0.02, false);
    current_motion_ = std::make_shared<MotionSequence>();
    current_motion_->ReserveCapacity(count, 29, 1, 1, 0, 0);
    current_motion_->timesteps = count;
    current_motion_->SetEncodeMode(0);
    std::array<double, 4> initial{};
    for (int i = 0; i < 4; ++i) {
      initial[i] = static_cast<float>(initial_robot[i]);
      init_ref_data_root_rot_array_[i] = quaternion[i];
    }
    heading_state_buffer_.SetData(HeadingState(initial, 0.0));
    for (int f = 0; f < count; ++f) {
      std::copy_n(quaternion + 4 * f, 4, current_motion_->BodyQuaternions(f)[0].begin());
      std::copy_n(joint + 29 * f, 29, current_motion_->JointPositions(f));
      std::copy_n(velocity + 29 * f, 29, current_motion_->JointVelocities(f));
    }
  }

  void Append(const double* pose, const double* velocity, const double* action) {
    // Match the float LowState boundary and double default subtraction in
    // GatherRobotStateToLogger; injected free-joint gyro is body-frame qvel.
    std::array<double, 4> base{};
    std::array<double, 3> angular{}, zero3{};
    std::array<double, 29> joint{}, speed{}, last{};
    for (int i = 0; i < 4; ++i) base[i] = static_cast<float>(pose[3 + i]);
    for (int i = 0; i < 3; ++i) angular[i] = static_cast<float>(velocity[3 + i]);
    for (int i = 0; i < 29; ++i) {
      const int hw = mujoco_to_isaaclab[i];
      joint[i] = static_cast<double>(static_cast<float>(pose[7 + hw])) - default_angles[hw];
      speed[i] = static_cast<float>(velocity[6 + hw]);
      last[i] = static_cast<float>(action[i]);
    }
    std::span<double> empty{};
    state_logger_->LogFullState(base, angular, zero3, base, angular, zero3,
      std::span(joint), std::span(speed), std::span(last), empty, empty, empty,
      empty, empty, empty, empty, false, false, {}, empty, empty, 0.0);
  }

  void Gather(int frame, bool play, float* encoder_out, float* history_out) {
    if (frame < 0 || frame >= current_motion_->timesteps || state_logger_->size() == 0)
      throw std::invalid_argument("invalid observation frame or missing state");
    current_frame_ = frame;
    operator_state.play = play;
    saved_frame_for_observation_window_ = 0;
    std::vector<double> encoder(1762, 0.0), history(930, 0.0);
    // Names, offsets and required G1-mode observations are checked against
    // the captured YAML and actual source registry by the Python builder.
    bool ok = GatherEncoderMode(encoder, 0, 3)
      && GatherMotionJointPositionsMultiFrame(encoder, 4, 10, 5)
      && GatherMotionJointVelocitiesMultiFrame(encoder, 294, 10, 5)
      && GatherMotionAnchorOrientationMutiFrame(encoder, 601, 10, 5)
      && GatherHisBaseAngularVelocity(history, 0, 10, 1)
      && GatherHisBodyJointPositions(history, 30, 10, 1)
      && GatherHisBodyJointVelocities(history, 320, 10, 1)
      && GatherHisLastActions(history, 610, 10, 1)
      && GatherHisGravityDir(history, 900, 10, 1);
    if (!ok) throw std::runtime_error("captured observation gatherer rejected input");
    std::transform(encoder.begin(), encoder.end(), encoder_out,
                   [](double value) { return static_cast<float>(value); });
    std::transform(history.begin(), history.end(), history_out,
                   [](double value) { return static_cast<float>(value); });
  }

  // Generated by extracting complete, unchanged methods from the captured
  // application translation unit. No SDK-bearing application is compiled.
  #include "captured_gatherers.inc"
};

static thread_local std::string witness_error;
extern "C" {
const char* sonic_observation_error() { return witness_error.c_str(); }
void* sonic_observation_create(int count, const double* quaternion, const double* joint,
                               const double* velocity, const double* initial_robot) {
  try {
    return new ObservationWitness(count, quaternion, joint, velocity, initial_robot);
  } catch (const std::exception& e) { witness_error = e.what(); return nullptr; }
}
void sonic_observation_destroy(void* pointer) { delete static_cast<ObservationWitness*>(pointer); }
int sonic_observation_append(void* pointer, const double* pose, const double* velocity, const double* action) {
  try {
    if (!pointer) throw std::invalid_argument("missing witness");
    static_cast<ObservationWitness*>(pointer)->Append(pose, velocity, action);
    return 0;
  } catch (const std::exception& e) { witness_error = e.what(); return -1; }
}
int sonic_observation_gather(void* pointer, int frame, int play, float* encoder, float* history) {
  try {
    if (!pointer) throw std::invalid_argument("missing witness");
    static_cast<ObservationWitness*>(pointer)->Gather(frame, play != 0, encoder, history);
    return 0;
  } catch (const std::exception& e) { witness_error = e.what(); return -1; }
}
}
